#!/bin/bash
readarray -t words
declare -A freq
for word in "${words[@]}"; do
  freq["$word"]=$((freq["$word"]+1))
done
for word in "${!freq[@]}"; do
  if (( "${freq[$word]}" == 1 )); then
    echo "$word"
  fi
done | sort
